name: CO2_Eddy
channels:
  - anaconda
  - defaults
dependencies:
  - numpy
  - pymysql
  - matplotlib
  - pymysql
  - pandas
  - rpy2
  - Ipython
  - tensorflow
  - pickle
  - pympler
  - memory_allocation
  - sklearn
  - keras
